config/routes.rb
Prueba::Application.routes.draw do
  resources :registro_alimentos

  resources :etiqueta

  resources :alimentos

  resources :medidas

  resources :platillos

  resources :menus

  resources :horarios

  resources :restaurants

  resources :historial_pesos

  resources :enfermedads

  resources :plan_alimenticios

  resources :usuarios

  resources :nutriologos

end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
	belongs_to :medida
	belongs_to :etiqueta
end

app/models/enfermedad.rb
class Enfermedad < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
end

app/models/etiqueta.rb
class Etiqueta < ActiveRecord::Base
    has_many :registro_alimentos
    has_many :alimentos
end

app/models/etiquetum.rb
class Etiquetum < ActiveRecord::Base
end

app/models/historial_peso.rb
class HistorialPeso < ActiveRecord::Base
	belongs_to :usuarios
end

app/models/horario.rb
class Horario < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/medida.rb
class Medida < ActiveRecord::Base
	has_many :alimentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :platillos
end

app/models/nutriologo.rb
class Nutriologo < ActiveRecord::Base
	has_many :plan_alimenticios
end

app/models/plan_alimenticio.rb
class PlanAlimenticio < ActiveRecord::Base
 	has_many :usuarios
	belongs_to :nutriologo
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
	belongs_to :menu
end

app/models/registro_alimento.rb
class RegistroAlimento < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :etiqueta
	belongs_to :alimento
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :horarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_one :historial_pesos
	has_one :plan_alimenticios
	has_many :registro_alimentos
	has_and_belongs_to_many :enfermedads
end

app/controllers/enfermedads_controller.rb
class EnfermedadsController < ApplicationController
  # GET /enfermedads
  # GET /enfermedads.xml
  def index
    @enfermedads = Enfermedad.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enfermedads }
    end
  end

  # GET /enfermedads/1
  # GET /enfermedads/1.xml
  def show
    @enfermedad = Enfermedad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enfermedad }
    end
  end

  # GET /enfermedads/new
  # GET /enfermedads/new.xml
  def new
    @enfermedad = Enfermedad.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enfermedad }
    end
  end

  # GET /enfermedads/1/edit
  def edit
    @enfermedad = Enfermedad.find(params[:id])
  end

  # POST /enfermedads
  # POST /enfermedads.xml
  def create
    @enfermedad = Enfermedad.new(params[:enfermedad])

    respond_to do |format|
      if @enfermedad.save
        format.html { redirect_to(@enfermedad, :notice => 'Enfermedad was successfully created.') }
        format.xml  { render :xml => @enfermedad, :status => :created, :location => @enfermedad }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enfermedad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enfermedads/1
  # PUT /enfermedads/1.xml
  def update
    @enfermedad = Enfermedad.find(params[:id])

    respond_to do |format|
      if @enfermedad.update_attributes(params[:enfermedad])
        format.html { redirect_to(@enfermedad, :notice => 'Enfermedad was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enfermedad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enfermedads/1
  # DELETE /enfermedads/1.xml
  def destroy
    @enfermedad = Enfermedad.find(params[:id])
    @enfermedad.destroy

    respond_to do |format|
      format.html { redirect_to(enfermedads_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/enfermedads_helper.rb
module EnfermedadsHelper
end

app/helpers/etiqueta_helper.rb
module EtiquetaHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/medidas_helper.rb
module MedidasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/enfermedads/_form.html.erb
<%= form_for(@enfermedad) do |f| %>
  <% if @enfermedad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enfermedad.errors.count, "error") %> prohibited this enfermedad from being saved:</h2>

      <ul>
      <% @enfermedad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enfermedads/edit.html.erb
<h1>Editing enfermedad</h1>

<%= render 'form' %>

<%= link_to 'Show', @enfermedad %> |
<%= link_to 'Back', enfermedads_path %>

app/views/enfermedads/index.html.erb
<h1>Listing enfermedads</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enfermedads.each do |enfermedad| %>
  <tr>
    <td><%= enfermedad.nombre %></td>
    <td><%= enfermedad.descripcion %></td>
    <td><%= link_to 'Show', enfermedad %></td>
    <td><%= link_to 'Edit', edit_enfermedad_path(enfermedad) %></td>
    <td><%= link_to 'Destroy', enfermedad, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enfermedad', new_enfermedad_path %>

app/views/enfermedads/new.html.erb
<h1>New enfermedad</h1>

<%= render 'form' %>

<%= link_to 'Back', enfermedads_path %>

app/views/enfermedads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @enfermedad.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @enfermedad.descripcion %>
</p>


<%= link_to 'Edit', edit_enfermedad_path(@enfermedad) %> |
<%= link_to 'Back', enfermedads_path %>