config/routes.rb
Prueba::Application.routes.draw do
  resources :registro_alimentos

  resources :etiqueta

  resources :alimentos

  resources :medidas

  resources :platillos

  resources :menus

  resources :horarios

  resources :restaurants

  resources :historial_pesos

  resources :enfermedads

  resources :plan_alimenticios

  resources :usuarios

  resources :nutriologos

end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
	belongs_to :medida
	belongs_to :etiqueta
end

app/models/enfermedad.rb
class Enfermedad < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
end

app/models/etiqueta.rb
class Etiqueta < ActiveRecord::Base
    has_many :registro_alimentos
    has_many :alimentos
end

app/models/etiquetum.rb
class Etiquetum < ActiveRecord::Base
end

app/models/historial_peso.rb
class HistorialPeso < ActiveRecord::Base
	belongs_to :usuarios
end

app/models/horario.rb
class Horario < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/medida.rb
class Medida < ActiveRecord::Base
	has_many :alimentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :platillos
end

app/models/nutriologo.rb
class Nutriologo < ActiveRecord::Base
	has_many :plan_alimenticios
end

app/models/plan_alimenticio.rb
class PlanAlimenticio < ActiveRecord::Base
 	has_many :usuarios
	belongs_to :nutriologo
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
	belongs_to :menu
end

app/models/registro_alimento.rb
class RegistroAlimento < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :etiqueta
	belongs_to :alimento
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :horarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_one :historial_pesos
	has_one :plan_alimenticios
	has_many :registro_alimentos
	has_and_belongs_to_many :enfermedads
end

app/controllers/nutriologos_controller.rb
class NutriologosController < ApplicationController
  # GET /nutriologos
  # GET /nutriologos.xml
  def index
    @nutriologos = Nutriologo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nutriologos }
    end
  end

  # GET /nutriologos/1
  # GET /nutriologos/1.xml
  def show
    @nutriologo = Nutriologo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @nutriologo }
    end
  end

  # GET /nutriologos/new
  # GET /nutriologos/new.xml
  def new
    @nutriologo = Nutriologo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @nutriologo }
    end
  end

  # GET /nutriologos/1/edit
  def edit
    @nutriologo = Nutriologo.find(params[:id])
  end

  # POST /nutriologos
  # POST /nutriologos.xml
  def create
    @nutriologo = Nutriologo.new(params[:nutriologo])

    respond_to do |format|
      if @nutriologo.save
        format.html { redirect_to(@nutriologo, :notice => 'Nutriologo was successfully created.') }
        format.xml  { render :xml => @nutriologo, :status => :created, :location => @nutriologo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @nutriologo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nutriologos/1
  # PUT /nutriologos/1.xml
  def update
    @nutriologo = Nutriologo.find(params[:id])

    respond_to do |format|
      if @nutriologo.update_attributes(params[:nutriologo])
        format.html { redirect_to(@nutriologo, :notice => 'Nutriologo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @nutriologo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nutriologos/1
  # DELETE /nutriologos/1.xml
  def destroy
    @nutriologo = Nutriologo.find(params[:id])
    @nutriologo.destroy

    respond_to do |format|
      format.html { redirect_to(nutriologos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/etiqueta_helper.rb
module EtiquetaHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/medidas_helper.rb
module MedidasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/nutriologos_helper.rb
module NutriologosHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/nutriologos/_form.html.erb
<%= form_for(@nutriologo) do |f| %>
  <% if @nutriologo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nutriologo.errors.count, "error") %> prohibited this nutriologo from being saved:</h2>

      <ul>
      <% @nutriologo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_pila %><br />
    <%= f.text_field :nombre_pila %>
  </div>
  <div class="field">
    <%= f.label :nombre_ap %><br />
    <%= f.text_field :nombre_ap %>
  </div>
  <div class="field">
    <%= f.label :nombre_am %><br />
    <%= f.text_field :nombre_am %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %><br />
    <%= f.date_select :fecha_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :direccion_calle %><br />
    <%= f.text_field :direccion_calle %>
  </div>
  <div class="field">
    <%= f.label :direccion_numero %><br />
    <%= f.text_field :direccion_numero %>
  </div>
  <div class="field">
    <%= f.label :direccion_colonia %><br />
    <%= f.text_field :direccion_colonia %>
  </div>
  <div class="field">
    <%= f.label :direccion_cp %><br />
    <%= f.text_field :direccion_cp %>
  </div>
  <div class="field">
    <%= f.label :direccion_cuidad %><br />
    <%= f.text_field :direccion_cuidad %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :cedula_profesional %><br />
    <%= f.text_field :cedula_profesional %>
  </div>
  <div class="field">
    <%= f.label :institucion %><br />
    <%= f.text_field :institucion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nutriologos/edit.html.erb
<h1>Editing nutriologo</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutriologo %> |
<%= link_to 'Back', nutriologos_path %>

app/views/nutriologos/index.html.erb
<h1>Listing nutriologos</h1>

<table>
  <tr>
    <th>Nombre pila</th>
    <th>Nombre ap</th>
    <th>Nombre am</th>
    <th>Email</th>
    <th>Password</th>
    <th>Fecha nacimiento</th>
    <th>Sexo</th>
    <th>Direccion calle</th>
    <th>Direccion numero</th>
    <th>Direccion colonia</th>
    <th>Direccion cp</th>
    <th>Direccion cuidad</th>
    <th>Telefono</th>
    <th>Cedula profesional</th>
    <th>Institucion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nutriologos.each do |nutriologo| %>
  <tr>
    <td><%= nutriologo.nombre_pila %></td>
    <td><%= nutriologo.nombre_ap %></td>
    <td><%= nutriologo.nombre_am %></td>
    <td><%= nutriologo.email %></td>
    <td><%= nutriologo.password %></td>
    <td><%= nutriologo.fecha_nacimiento %></td>
    <td><%= nutriologo.sexo %></td>
    <td><%= nutriologo.direccion_calle %></td>
    <td><%= nutriologo.direccion_numero %></td>
    <td><%= nutriologo.direccion_colonia %></td>
    <td><%= nutriologo.direccion_cp %></td>
    <td><%= nutriologo.direccion_cuidad %></td>
    <td><%= nutriologo.telefono %></td>
    <td><%= nutriologo.cedula_profesional %></td>
    <td><%= nutriologo.institucion %></td>
    <td><%= link_to 'Show', nutriologo %></td>
    <td><%= link_to 'Edit', edit_nutriologo_path(nutriologo) %></td>
    <td><%= link_to 'Destroy', nutriologo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nutriologo', new_nutriologo_path %>

app/views/nutriologos/new.html.erb
<h1>New nutriologo</h1>

<%= render 'form' %>

<%= link_to 'Back', nutriologos_path %>

app/views/nutriologos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre pila:</b>
  <%= @nutriologo.nombre_pila %>
</p>

<p>
  <b>Nombre ap:</b>
  <%= @nutriologo.nombre_ap %>
</p>

<p>
  <b>Nombre am:</b>
  <%= @nutriologo.nombre_am %>
</p>

<p>
  <b>Email:</b>
  <%= @nutriologo.email %>
</p>

<p>
  <b>Password:</b>
  <%= @nutriologo.password %>
</p>

<p>
  <b>Fecha nacimiento:</b>
  <%= @nutriologo.fecha_nacimiento %>
</p>

<p>
  <b>Sexo:</b>
  <%= @nutriologo.sexo %>
</p>

<p>
  <b>Direccion calle:</b>
  <%= @nutriologo.direccion_calle %>
</p>

<p>
  <b>Direccion numero:</b>
  <%= @nutriologo.direccion_numero %>
</p>

<p>
  <b>Direccion colonia:</b>
  <%= @nutriologo.direccion_colonia %>
</p>

<p>
  <b>Direccion cp:</b>
  <%= @nutriologo.direccion_cp %>
</p>

<p>
  <b>Direccion cuidad:</b>
  <%= @nutriologo.direccion_cuidad %>
</p>

<p>
  <b>Telefono:</b>
  <%= @nutriologo.telefono %>
</p>

<p>
  <b>Cedula profesional:</b>
  <%= @nutriologo.cedula_profesional %>
</p>

<p>
  <b>Institucion:</b>
  <%= @nutriologo.institucion %>
</p>


<%= link_to 'Edit', edit_nutriologo_path(@nutriologo) %> |
<%= link_to 'Back', nutriologos_path %>