config/routes.rb
Prueba::Application.routes.draw do
  resources :registro_alimentos

  resources :etiqueta

  resources :alimentos

  resources :medidas

  resources :platillos

  resources :menus

  resources :horarios

  resources :restaurants

  resources :historial_pesos

  resources :enfermedads

  resources :plan_alimenticios

  resources :usuarios

  resources :nutriologos

end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
	belongs_to :medida
	belongs_to :etiqueta
end

app/models/enfermedad.rb
class Enfermedad < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
end

app/models/etiqueta.rb
class Etiqueta < ActiveRecord::Base
    has_many :registro_alimentos
    has_many :alimentos
end

app/models/etiquetum.rb
class Etiquetum < ActiveRecord::Base
end

app/models/historial_peso.rb
class HistorialPeso < ActiveRecord::Base
	belongs_to :usuarios
end

app/models/horario.rb
class Horario < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/medida.rb
class Medida < ActiveRecord::Base
	has_many :alimentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :platillos
end

app/models/nutriologo.rb
class Nutriologo < ActiveRecord::Base
	has_many :plan_alimenticios
end

app/models/plan_alimenticio.rb
class PlanAlimenticio < ActiveRecord::Base
 	has_many :usuarios
	belongs_to :nutriologo
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
	belongs_to :menu
end

app/models/registro_alimento.rb
class RegistroAlimento < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :etiqueta
	belongs_to :alimento
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :horarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_one :historial_pesos
	has_one :plan_alimenticios
	has_many :registro_alimentos
	has_and_belongs_to_many :enfermedads
end

app/controllers/alimentos_controller.rb
class AlimentosController < ApplicationController
  # GET /alimentos
  # GET /alimentos.xml
  def index
    @alimentos = Alimento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alimentos }
    end
  end

  # GET /alimentos/1
  # GET /alimentos/1.xml
  def show
    @alimento = Alimento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alimento }
    end
  end

  # GET /alimentos/new
  # GET /alimentos/new.xml
  def new
    @alimento = Alimento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alimento }
    end
  end

  # GET /alimentos/1/edit
  def edit
    @alimento = Alimento.find(params[:id])
  end

  # POST /alimentos
  # POST /alimentos.xml
  def create
    @alimento = Alimento.new(params[:alimento])

    respond_to do |format|
      if @alimento.save
        format.html { redirect_to(@alimento, :notice => 'Alimento was successfully created.') }
        format.xml  { render :xml => @alimento, :status => :created, :location => @alimento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alimentos/1
  # PUT /alimentos/1.xml
  def update
    @alimento = Alimento.find(params[:id])

    respond_to do |format|
      if @alimento.update_attributes(params[:alimento])
        format.html { redirect_to(@alimento, :notice => 'Alimento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alimentos/1
  # DELETE /alimentos/1.xml
  def destroy
    @alimento = Alimento.find(params[:id])
    @alimento.destroy

    respond_to do |format|
      format.html { redirect_to(alimentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/etiqueta_helper.rb
module EtiquetaHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/medidas_helper.rb
module MedidasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/alimentos/_form.html.erb
<%= form_for(@alimento) do |f| %>
  <% if @alimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alimento.errors.count, "error") %> prohibited this alimento from being saved:</h2>

      <ul>
      <% @alimento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :calorias %><br />
    <%= f.text_field :calorias %>
  </div>
  <div class="field">
    <%= f.label :grasas_saturadas %><br />
    <%= f.text_field :grasas_saturadas %>
  </div>
  <div class="field">
    <%= f.label :grasas_trans %><br />
    <%= f.text_field :grasas_trans %>
  </div>
  <div class="field">
    <%= f.label :proteinas %><br />
    <%= f.text_field :proteinas %>
  </div>
  <div class="field">
    <%= f.label :colesterol %><br />
    <%= f.text_field :colesterol %>
  </div>
  <div class="field">
    <%= f.label :fibra %><br />
    <%= f.text_field :fibra %>
  </div>
  <div class="field">
    <%= f.label :azucares %><br />
    <%= f.text_field :azucares %>
  </div>
  <div class="field">
    <%= f.label :potasio %><br />
    <%= f.text_field :potasio %>
  </div>
  <div class="field">
    <%= f.label :carbohidratos %><br />
    <%= f.text_field :carbohidratos %>
  </div>
  <div class="field">
    <%= f.label :fosforo %><br />
    <%= f.text_field :fosforo %>
  </div>
  <div class="field">
    <%= f.label :sodio %><br />
    <%= f.text_field :sodio %>
  </div>
  <div class="field">
    <%= f.label :calcio %><br />
    <%= f.text_field :calcio %>
  </div>
  <div class="field">
    <%= f.label :hierro %><br />
    <%= f.text_field :hierro %>
  </div>
  <div class="field">
    <%= f.label :aceites %><br />
    <%= f.text_field :aceites %>
  </div>
  <div class="field">
    <%= f.label :vitamina_c %><br />
    <%= f.text_field :vitamina_c %>
  </div>
  <div class="field">
    <%= f.label :vitamina_a %><br />
    <%= f.text_field :vitamina_a %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :medida %><br />
    <%= f.text_field :medida %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alimentos/edit.html.erb
<h1>Editing alimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @alimento %> |
<%= link_to 'Back', alimentos_path %>

app/views/alimentos/index.html.erb
<h1>Listing alimentos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Calorias</th>
    <th>Grasas saturadas</th>
    <th>Grasas trans</th>
    <th>Proteinas</th>
    <th>Colesterol</th>
    <th>Fibra</th>
    <th>Azucares</th>
    <th>Potasio</th>
    <th>Carbohidratos</th>
    <th>Fosforo</th>
    <th>Sodio</th>
    <th>Calcio</th>
    <th>Hierro</th>
    <th>Aceites</th>
    <th>Vitamina c</th>
    <th>Vitamina a</th>
    <th>Cantidad</th>
    <th>Medida</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alimentos.each do |alimento| %>
  <tr>
    <td><%= alimento.nombre %></td>
    <td><%= alimento.descripcion %></td>
    <td><%= alimento.calorias %></td>
    <td><%= alimento.grasas_saturadas %></td>
    <td><%= alimento.grasas_trans %></td>
    <td><%= alimento.proteinas %></td>
    <td><%= alimento.colesterol %></td>
    <td><%= alimento.fibra %></td>
    <td><%= alimento.azucares %></td>
    <td><%= alimento.potasio %></td>
    <td><%= alimento.carbohidratos %></td>
    <td><%= alimento.fosforo %></td>
    <td><%= alimento.sodio %></td>
    <td><%= alimento.calcio %></td>
    <td><%= alimento.hierro %></td>
    <td><%= alimento.aceites %></td>
    <td><%= alimento.vitamina_c %></td>
    <td><%= alimento.vitamina_a %></td>
    <td><%= alimento.cantidad %></td>
    <td><%= alimento.medida %></td>
    <td><%= link_to 'Show', alimento %></td>
    <td><%= link_to 'Edit', edit_alimento_path(alimento) %></td>
    <td><%= link_to 'Destroy', alimento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alimento', new_alimento_path %>

app/views/alimentos/new.html.erb
<h1>New alimento</h1>

<%= render 'form' %>

<%= link_to 'Back', alimentos_path %>

app/views/alimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @alimento.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @alimento.descripcion %>
</p>

<p>
  <b>Calorias:</b>
  <%= @alimento.calorias %>
</p>

<p>
  <b>Grasas saturadas:</b>
  <%= @alimento.grasas_saturadas %>
</p>

<p>
  <b>Grasas trans:</b>
  <%= @alimento.grasas_trans %>
</p>

<p>
  <b>Proteinas:</b>
  <%= @alimento.proteinas %>
</p>

<p>
  <b>Colesterol:</b>
  <%= @alimento.colesterol %>
</p>

<p>
  <b>Fibra:</b>
  <%= @alimento.fibra %>
</p>

<p>
  <b>Azucares:</b>
  <%= @alimento.azucares %>
</p>

<p>
  <b>Potasio:</b>
  <%= @alimento.potasio %>
</p>

<p>
  <b>Carbohidratos:</b>
  <%= @alimento.carbohidratos %>
</p>

<p>
  <b>Fosforo:</b>
  <%= @alimento.fosforo %>
</p>

<p>
  <b>Sodio:</b>
  <%= @alimento.sodio %>
</p>

<p>
  <b>Calcio:</b>
  <%= @alimento.calcio %>
</p>

<p>
  <b>Hierro:</b>
  <%= @alimento.hierro %>
</p>

<p>
  <b>Aceites:</b>
  <%= @alimento.aceites %>
</p>

<p>
  <b>Vitamina c:</b>
  <%= @alimento.vitamina_c %>
</p>

<p>
  <b>Vitamina a:</b>
  <%= @alimento.vitamina_a %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @alimento.cantidad %>
</p>

<p>
  <b>Medida:</b>
  <%= @alimento.medida %>
</p>


<%= link_to 'Edit', edit_alimento_path(@alimento) %> |
<%= link_to 'Back', alimentos_path %>