config/routes.rb
Prueba::Application.routes.draw do
  resources :registro_alimentos

  resources :etiqueta

  resources :alimentos

  resources :medidas

  resources :platillos

  resources :menus

  resources :horarios

  resources :restaurants

  resources :historial_pesos

  resources :enfermedads

  resources :plan_alimenticios

  resources :usuarios

  resources :nutriologos

end

app/models/alimento.rb
class Alimento < ActiveRecord::Base
	belongs_to :medida
	belongs_to :etiqueta
end

app/models/enfermedad.rb
class Enfermedad < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
end

app/models/etiqueta.rb
class Etiqueta < ActiveRecord::Base
    has_many :registro_alimentos
    has_many :alimentos
end

app/models/etiquetum.rb
class Etiquetum < ActiveRecord::Base
end

app/models/historial_peso.rb
class HistorialPeso < ActiveRecord::Base
	belongs_to :usuarios
end

app/models/horario.rb
class Horario < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/medida.rb
class Medida < ActiveRecord::Base
	has_many :alimentos
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :platillos
end

app/models/nutriologo.rb
class Nutriologo < ActiveRecord::Base
	has_many :plan_alimenticios
end

app/models/plan_alimenticio.rb
class PlanAlimenticio < ActiveRecord::Base
 	has_many :usuarios
	belongs_to :nutriologo
end

app/models/platillo.rb
class Platillo < ActiveRecord::Base
	belongs_to :menu
end

app/models/registro_alimento.rb
class RegistroAlimento < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :etiqueta
	belongs_to :alimento
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :horarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_one :historial_pesos
	has_one :plan_alimenticios
	has_many :registro_alimentos
	has_and_belongs_to_many :enfermedads
end

app/controllers/plan_alimenticios_controller.rb
class PlanAlimenticiosController < ApplicationController
  # GET /plan_alimenticios
  # GET /plan_alimenticios.xml
  def index
    @plan_alimenticios = PlanAlimenticio.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plan_alimenticios }
    end
  end

  # GET /plan_alimenticios/1
  # GET /plan_alimenticios/1.xml
  def show
    @plan_alimenticio = PlanAlimenticio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan_alimenticio }
    end
  end

  # GET /plan_alimenticios/new
  # GET /plan_alimenticios/new.xml
  def new
    @plan_alimenticio = PlanAlimenticio.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan_alimenticio }
    end
  end

  # GET /plan_alimenticios/1/edit
  def edit
    @plan_alimenticio = PlanAlimenticio.find(params[:id])
  end

  # POST /plan_alimenticios
  # POST /plan_alimenticios.xml
  def create
    @plan_alimenticio = PlanAlimenticio.new(params[:plan_alimenticio])

    respond_to do |format|
      if @plan_alimenticio.save
        format.html { redirect_to(@plan_alimenticio, :notice => 'Plan alimenticio was successfully created.') }
        format.xml  { render :xml => @plan_alimenticio, :status => :created, :location => @plan_alimenticio }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan_alimenticio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plan_alimenticios/1
  # PUT /plan_alimenticios/1.xml
  def update
    @plan_alimenticio = PlanAlimenticio.find(params[:id])

    respond_to do |format|
      if @plan_alimenticio.update_attributes(params[:plan_alimenticio])
        format.html { redirect_to(@plan_alimenticio, :notice => 'Plan alimenticio was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan_alimenticio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plan_alimenticios/1
  # DELETE /plan_alimenticios/1.xml
  def destroy
    @plan_alimenticio = PlanAlimenticio.find(params[:id])
    @plan_alimenticio.destroy

    respond_to do |format|
      format.html { redirect_to(plan_alimenticios_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/etiqueta_helper.rb
module EtiquetaHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/medidas_helper.rb
module MedidasHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/plan_alimenticios_helper.rb
module PlanAlimenticiosHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/plan_alimenticios/_form.html.erb
<%= form_for(@plan_alimenticio) do |f| %>
  <% if @plan_alimenticio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan_alimenticio.errors.count, "error") %> prohibited this plan_alimenticio from being saved:</h2>

      <ul>
      <% @plan_alimenticio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :calorias %><br />
    <%= f.text_field :calorias %>
  </div>
  <div class="field">
    <%= f.label :fibras %><br />
    <%= f.text_field :fibras %>
  </div>
  <div class="field">
    <%= f.label :azucares %><br />
    <%= f.text_field :azucares %>
  </div>
  <div class="field">
    <%= f.label :carbohidratos %><br />
    <%= f.text_field :carbohidratos %>
  </div>
  <div class="field">
    <%= f.label :proteinas %><br />
    <%= f.text_field :proteinas %>
  </div>
  <div class="field">
    <%= f.label :ingestas %><br />
    <%= f.text_field :ingestas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plan_alimenticios/edit.html.erb
<h1>Editing plan_alimenticio</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan_alimenticio %> |
<%= link_to 'Back', plan_alimenticios_path %>

app/views/plan_alimenticios/index.html.erb
<h1>Listing plan_alimenticios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Calorias</th>
    <th>Fibras</th>
    <th>Azucares</th>
    <th>Carbohidratos</th>
    <th>Proteinas</th>
    <th>Ingestas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plan_alimenticios.each do |plan_alimenticio| %>
  <tr>
    <td><%= plan_alimenticio.nombre %></td>
    <td><%= plan_alimenticio.descripcion %></td>
    <td><%= plan_alimenticio.calorias %></td>
    <td><%= plan_alimenticio.fibras %></td>
    <td><%= plan_alimenticio.azucares %></td>
    <td><%= plan_alimenticio.carbohidratos %></td>
    <td><%= plan_alimenticio.proteinas %></td>
    <td><%= plan_alimenticio.ingestas %></td>
    <td><%= link_to 'Show', plan_alimenticio %></td>
    <td><%= link_to 'Edit', edit_plan_alimenticio_path(plan_alimenticio) %></td>
    <td><%= link_to 'Destroy', plan_alimenticio, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plan alimenticio', new_plan_alimenticio_path %>

app/views/plan_alimenticios/new.html.erb
<h1>New plan_alimenticio</h1>

<%= render 'form' %>

<%= link_to 'Back', plan_alimenticios_path %>

app/views/plan_alimenticios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @plan_alimenticio.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @plan_alimenticio.descripcion %>
</p>

<p>
  <b>Calorias:</b>
  <%= @plan_alimenticio.calorias %>
</p>

<p>
  <b>Fibras:</b>
  <%= @plan_alimenticio.fibras %>
</p>

<p>
  <b>Azucares:</b>
  <%= @plan_alimenticio.azucares %>
</p>

<p>
  <b>Carbohidratos:</b>
  <%= @plan_alimenticio.carbohidratos %>
</p>

<p>
  <b>Proteinas:</b>
  <%= @plan_alimenticio.proteinas %>
</p>

<p>
  <b>Ingestas:</b>
  <%= @plan_alimenticio.ingestas %>
</p>


<%= link_to 'Edit', edit_plan_alimenticio_path(@plan_alimenticio) %> |
<%= link_to 'Back', plan_alimenticios_path %>